# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: aperturesci.jfrog.io/demo-docker/vote
  tag: pr-3-fd15d3e
redis:
  usePassword: false
replicaCount: 1
