# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: aperturesci.jfrog.io/demo-docker/vote
  tag: pr-18-update-vote-dogs-vs-cats-5677c0f
redis:
  usePassword: false
replicaCount: 1
