# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: aperturesci.jfrog.io/demo-docker/worker
  tag: pr-17-modify-worker-0a0a983
redis:
  usePassword: false
replicaCount: 1
